### ISSUE TITLE
Causing 403 errors - "The link you have followed has expired"

### ISSUE THREAD

**Issue by n9yty** [alleyinteractive/apple-news#530] opened 2018-06-27 23:08 UTC
After the upgrade to v1.4.0 we started seeing errors on the site when doing updates, whether pages, posts, Woocommerce orders, etc...  The update would go through in Wordpress, but we would get redirected to a page saying "The link you have followed has expired."  From my reading, the core error seems to be nonce related.

I see you have updated a lot of pieces of the codebase for v1.4.0 to incorporate more nonce checking, is it possible that something is going wrong?  The initial nonce check by Wordpress seems OK, as the underlying information is updated, but still we are redirected to the error page which might be related to a further call by this plugin to verify a nonce.

Disabling the plugin or reverting to v1.3.0 makes the issue go away.

**Comment by marchesinij** [comment] 2018-06-29 04:57
Apple News Wordpress plug-in team,

The issue above is a critical bug impacting v1.4.0.  You can replicate the issue by adding the Events calendar Wordpress plug-in to the site.  You will receive this error when updating an existing event or adding a new one.

https://wordpress.org/plugins/the-events-calendar/

**Comment by webzunft** [comment] 2018-07-02 07:49
The same happens with the https://wordpress.org/plugins/advanced-ads/. Just create a new ad to see the error.

**Comment by danielbachhuber** [comment] 2018-08-17 14:49
Duplicate of #544

**Comment by kevinfodness** [comment] 2018-09-07 09:51
Closing as a dupe.

**Comment by n9yty** [comment] 2018-09-12 19:27
I'm confused, so has a release been made that contaisn this fix?  The last I see in the plugin update is v1.4.2 which still had the problem on our site, and that was from four weeks ago?  Just asking so I know whether our problem is really fixed or not, and need to know what I'm testing. Thanks.

**Comment by kevinfodness** [comment] 2018-09-14 10:01
Hi @n9yty —

Versions 1.4.1 and 1.4.2 both contained fixes for this particular error, but if you're still experiencing it on v1.4.2 then it's possible that we missed a use case. Can you walk me through the steps to reproduce, please?

**Comment by n9yty** [comment] 2018-09-14 14:40
After we activated it, we were constantly getting the 403 error in the subject. We weren’t doing anything in the plugin itself, it was affecting  operation in the admin side. It has been a month now, it is not as clear in my memory, but I believe it was especially bad for operations affecting saving posts, or things that use custom post types like woocommerce order updates.

**Comment by kevinfodness** [comment] 2018-09-14 14:56
My guess is that it's a conflict with another plugin that's loading something in a way that we don't expect. We don't experience this behavior on a vanilla install. I'll reopen this issue and conduct an audit of all of the places where we're doing nonce verification to see if there are one or more that could be causing this issue. Thanks for the details!

**Closed** 2020-10-05 18:25 UTC
Labels: bug, evaluating
