### ISSUE TITLE
INVALID_DOCUMENT - "text" was "" should be not (null or an empty string)

### ISSUE THREAD

**Issue by protoolreviews** [alleyinteractive/apple-news#260] opened 2016-12-26 14:41 UTC
There has been an error with the API:
INVALID_DOCUMENT - "text" was "" should be not (null or an empty string) (keyPath components->2->components->153->text)
INVALID_DOCUMENT - no components defined for role=heading3 (keyPath components->2->components->153)

**Comment by bcampeau** [comment] 2016-12-26 15:06
This is a duplicate of #205

**Closed by bcampeau** 2016-12-26 15:06 UTC
