### ISSUE TITLE
Updated the Plugin and it conflicts with Visual Editor

### ISSUE THREAD

**Issue by salzburg917k** [alleyinteractive/apple-news#317] opened 2017-02-16 02:04 UTC
Updated the plugin to the latest version and it conflicts with Visual Editor. Causing the icons to disappear as well as the black text content to go white.

Have tried various fixed to make the text go black - but the only way to solve it is to deactivate the plugin as it conflicts. 

![white text](https://cloud.githubusercontent.com/assets/25808439/23004037/40f874f2-f3ec-11e6-9520-8913ea6f0dd0.png)

**Comment by bcampeau** [comment] 2017-02-16 02:08
We don't officially support compatibility with third party plugins. Have you inspected what style(s) are conflicting?

**Comment by salzburg917k** [comment] 2017-02-16 17:27
Hi, third party Plugin was a side issue. The main issue is when updating to the latest version 1.2.3 it screws up visual editor and makes the input box for adding/editing a post go white and it removes the editor icons (see screen grab).

The update conflicts with WP. Or is it just my theme ?

**Comment by bcampeau** [comment] 2017-02-16 17:28
We're looking into it

**Comment by kevinfodness** [comment] 2017-02-16 18:02
@salzburg917k—

I can't reproduce this on my end, so any additional info you could provide would be helpful:

1. Can you let me know if you are seeing any errors in the JavaScript console?
2. Does the problem go away if you load the site in an incognito or private window?
3. What theme are you using?
4. What other plugins are active?
5. What is the version of WordPress you are using?
6. Does the problem go away if you switch to the Twenty Seventeen theme?

**Comment by pestevez** [comment] 2017-03-14 18:52
+1

**Comment by kevinfodness** [comment] 2017-03-14 19:24
Hi @pestevez —

Thanks for the report. I'm using the same settings in my installation (Twenty Seventeen, WordPress 4.7.3, Publish to Apple News being the only active plugin) and I'm not seeing this issue. If you have this installed in a test environment, would it be possible to send me an export of your database, scrubbed of any identifying information (Apple News client IDs/etc)?

**Comment by pestevez** [comment] 2017-03-14 19:52
Hey @kevinfodness - I just sent you an email with more details. Thanks

**Comment by kevinfodness** [comment] 2017-03-20 18:28
It appears that the issue for @pestevez was that the plugin was not fully configured. The error message on the post edit screen was halting the page load, so the JavaScript for TinyMCE never loaded, which caused the issue.

I think a variation of the same situation may be the culprit for @salzburg917k. I'm opening a separate issue to address how we handle errors to make the plugin more fault-tolerant.

**Comment by kevinfodness** [comment] 2017-03-20 18:33
Closing this in favor of #341.

**Closed by kevinfodness** 2017-03-20 18:33 UTC
Labels: duplicate
