### ISSUE TITLE
Error message and articles stuck, not publishing

### ISSUE THREAD

**Issue by mrosarionyc** [alleyinteractive/apple-news#399] opened 2017-07-25 15:06 UTC
![applenews-wp-error](https://user-images.githubusercontent.com/30440245/28578828-d539af50-7128-11e7-93c1-b91606a66e2e.PNG)

**Version 1.2.3**

Hi. We're noticing issues with our articles and are trying to figure out how to address. 
1. The majority of our articles have not published to apple news (they either say 'pending' or 'not published'
2. Trying the reset and publish buttons results in an error message (see attached screenshot): _There has been an error with the API: INVALID_DOCUMENT - "text" was "" should be not (null or an empty string) (keyPath components->1->components->8->text)_
3. Even though we have the plug-in setup to publish automatically, the posts do not publish to Apple News

Will appreciate your help with this.

Thanks,
Miguel
![signature-wpdashboard-errors](https://user-images.githubusercontent.com/30440245/28628610-1720ecec-71f3-11e7-8e93-d99556afef83.PNG)

![wp-applenews-errors](https://user-images.githubusercontent.com/30440245/28629252-ecc8a92e-71f4-11e7-87a0-9bd83cc9613a.PNG)

**Comment by kevinfodness** [comment] 2017-08-04 15:17
It appears that all three issues are being caused by blank lines in the content. We've got outstanding issues to address this more proactively in the plugin: #365, #205.

However, in the interim, you should ensure that you don't have blank lines in your content (e.g., hitting return twice between paragraphs). The error output is giving you the exact location in the generated JSON where this is occurring, so if you download the JSON from the main Apple News screen, you can locate the source of the problem. You can also search for `""` in the generated JSON.

**Comment by kevinfodness** [comment] 2017-08-04 15:48
Closing as duplicate of #365 and #205.

**Closed by kevinfodness** 2017-08-04 15:48 UTC
Labels: duplicate

**Comment by mrosarionyc** [comment] 2017-08-04 16:46
Thanks @kevinfodness! I was able to clear the errors by upgrading the plug-in to 1.2.7 and by disabling "Enable HTML Support". Since that was an experimental feature, it is ok to keep it disabled, correct?

**Comment by kevinfodness** [comment] 2017-08-04 18:27
Yes, that's correct. The plugin default is to use Markdown and not HTML, but you can enable HTML if you wish. As long as the output is what you expect, there is no harm in leaving HTML support off.
