### ISSUE TITLE
WordPress critical error caused by publishing article with multiple animated GIFs

### ISSUE THREAD

**Issue by adamengst** [alleyinteractive/apple-news#893] opened 2021-09-23 15:59 UTC
When I try to publish this article:

https://tidbits.com/2021/09/23/center-stage-keeps-you-in-the-video-chat-frame/

to Apple News, my WordPress site throws a critical error:

![image](https://user-images.githubusercontent.com/36641103/134541840-90325867-6ac6-4a9e-a07e-946f379a6d0a.png)

I was able to work around the issue by disabling Publish to Apple News temporarily, publishing the article (it was actually published, but the plugin crash prevented some aspects of the publish process from completing, such as posting to our Discourse site), and reenabling Publish to Apple News.

I believe the problem is related to the article containing multiple animated GIFs since I've never seen this error before (and we have published at least one animated GIF in an article before). Feel free to grab the content of the article for testing.

Here are the details from the WordPress email:

> Howdy!
> 
> Since WordPress 5.2 there is a built-in feature that detects when a plugin or theme causes a fatal error on your site, and notifies you with this automated email.
> 
> In this case, WordPress caught an error with one of your plugins, Publish to Apple News.
> 
> First, visit your website (https://tidbits.com/) and check for any visible issues. Next, visit the page where the error was caught (https://tidbits.com/wp/wp-admin/post.php) and check for any visible issues.
> 
> Please contact your host for assistance with investigating this issue further.
> 
> If your site appears broken and you can't access your dashboard normally, WordPress now has a special "recovery mode". This lets you safely login to your dashboard and investigate further.
> 
> https://tidbits.com/wp/wp-login.php?action=enter_recovery_mode&rm_token=nzOGkB5dOk7ybyiIH1fvw3&rm_key=gzHUpEZ4dihzKTznDak1a5
> 
> To keep your site safe, this link will expire in 1 day. Don't worry about that, though: a new link will be emailed to you if the error occurs again after it expires.
> 
> When seeking help with this issue, you may be asked for some of the following information:
> WordPress version 5.7.2
> Current theme: TidBITS (version )
> Current plugin: Publish to Apple News (version 2.1.2)
> PHP version 7.2.24-0ubuntu0.18.04.8
> 
> Error Details
> =============
> An error of type E_ERROR was caused in line 308 of the file /storage/av04814/www/public_html/public/app/plugins/publish-to-apple-news/includes/apple-push-api/request/class-request.php. Error message: Allowed memory size of 268435456 bytes exhausted (tried to allocate 141980544 bytes)

**Comment by kevinfodness** [comment] 2021-09-29 20:51
Do you have the remote images setting enabled? The process crashed because PHP ran out of memory, which could be caused by trying to bundle images, which would be the case if use remote images was set to "no." We strongly recommend that the use remote images setting is set to "yes."

**Comment by adamengst** [comment] 2021-09-29 21:50
Yes, remote images was set to No, but changing it to Yes did not make a difference. I still got the same crash and error. I tried enabling debugging but didn't receive anything, likely because the publish isn't completing.

**Comment by kevinfodness** [comment] 2021-09-30 13:49
Yeah, that would make sense that you wouldn't receive the message, since the process is likely dying before it reaches that point.

My guess is that you've got a plugin or some logic in your theme that's causing an infinite loop during the Apple News publish operation, and the memory usage is piling up until it hits PHP's limit and the process dies.

Let's try to isolate this a bit - can you try downloading the article JSON? In the WordPress admin, click on *Apple News* and it will show you your article list, then find the article that is failing, hover over it, and click the *Download* link. Does that succeed, or do you get the same error?

The next thing I would try is to disable all plugins except the Publish to Apple News plugin in a test environment and see if the problem persists. If it does not, then you can re-activate the plugins one by one until you figure out which one is causing the problem. If it does, then the problem is likely with your theme. You should be able to switch to a built-in theme, like Twenty Twenty One, in order to test this (if you switch to a built-in theme and the error does not occur, then the problem is located in your theme).

Unfortunately, we cannot provide support in the plugin for all third party plugins and themes, but knowing which plugin or theme is causing the issue is a good place to start. I would guess that the problem is likely related to the fact that the Publish to Apple News plugin needs to run `the_content` filter on your post content in order to prepare the HTML that it parses to turn into an article, and that's causing a conflict with one of your plugins or themes.

**Comment by adamengst** [comment] 2021-10-05 20:07
Sorry for the delay, Kevin. Unfortunately, we haven’t done development on
this site for a long time so I don’t have access to an up-to-date staging
environment and disabling the plugins would render the production site
non-functional.

Downloading the JSON does work fine (attached).

I’m not too stressed about this, since it’s the first time I’ve ever had
the problem and it’s almost certainly associated with an article having too
many animated GIFs. Another article with just one or two was fine.

cheers… -Adam

**Comment by kevinfodness** [comment] 2021-10-18 22:19
Yep, I'd agree that it's likely due to the image sizes, and it's likely related to the processing that is being done in order to send the article to Apple's servers, which is a bit different from what is done to download it. I'm going to go ahead and close this issue, since it appears to be a resourcing issue with a post with large images, but let me know if the issue seems more widespread.

**Closed as completed by kevinfodness** 2021-10-18 22:19 UTC
