### ISSUE TITLE
Apple News Error Message/Invalid_Document

### ISSUE THREAD

**Issue by johnllyman** [alleyinteractive/apple-news#863] opened 2021-07-07 04:55 UTC
I would guess I'm probably getting the same or similar issue below as others.  Is there an easy fix? Thank you for updating the plugin and my hope was that the update would fix a longstanding tech glitch with the plugin.

There has been an error with the Apple News API: INVALID_DOCUMENT - Document has missing references. Couldn't find ComponentTextStyle on document for id: default-pullquote and, no inline value set!

If you need assistance, please reach out for support on WordPress.org or GitHub.

**Comment by soulseekah** [comment] 2021-08-14 16:39
Duplicate of https://github.com/alleyinteractive/apple-news/issues/815

**Comment by kevinfodness** [comment] 2021-08-16 14:18
Closing as a duplicate. There is an open PR relating to this issue that I'm going to evaluate as a possible fix.

**Closed as completed by kevinfodness** 2021-08-16 14:18 UTC
Labels: duplicate
