### ISSUE TITLE
Apple news image alignment isssue

### ISSUE THREAD

**Issue by RamyaVelan** [alleyinteractive/apple-news#472] opened 2018-05-01 05:47 UTC
I have faced one issue. That is when I have used any one of the image alignment like left,right and center alignment in my post, the enclosed or nearby paragraphs are comes into a single body role.

After publishing such type of image aligned post returns some issue.

For example, if the post has no alignment image , every the paragraphs are comes under separate body role.

For example JSON format for normal post:
{
    role : body,
    text : "<p.>paragraph1</p.>"
    format : html
} 
{
    role : image,
    URL : "http://bundle-image.jpg"
}
{
    role : body,
    text : "<p.> paragraph2</p.>"
    format : html
} 
{
    role : body,
    text : "<p.> paragraph3</p.>"
    format : html
} 

But if the post has any one of the image alignment,
JSON for this format of post,
{
    role : body,
    text : "<p.> paragraph1</p.>"
    format : html
} 
{
    role : image,
    URL : "http://bundle-image.jpg"
}
{
    role : body,
    text : "<p.> paragraph2</p.><p.> paragraph3</p.>"
    format : html
} 

**Note :** Instead of <p> and </p> tag I have used <p.> and </p.>
So styles are applied only to the body tag. At last of paragraph2 and at first of pargarph3 has no styles are added. Especially paragraph spacing before and after was not added to that paragraphs (paragraph2 and paragraph3).

Kindly check this issue and do the needful.

**Comment by kevinfodness** [comment] 2018-09-07 09:44
Hi @RamyaVelan — I can't reproduce this behavior using HTML format and the latest version of the plugin, so I'm going to close this issue.

**Closed by kevinfodness** 2018-09-07 09:44 UTC
Labels: evaluating
