### ISSUE TITLE
Article Errors

### ISSUE THREAD

**Issue by VenusVenus** [alleyinteractive/apple-news#353] opened 2017-04-13 20:18 UTC
Hello, I installed and configured everything based on GITHUB and this is the error I receive when trying to publish.  Can you tell me what I did wrong?  Thank you. 

API Response:
Array
(
    [headers] => Requests_Utility_CaseInsensitiveDictionary Object
        (
            [data:protected] => Array
                (
                    [date] => Thu, 13 Apr 2017 20:05:23 GMT
                    [request-id] => 7340acae-14e5-442e-9cef-c8ab51168aa0
                    [content-type] => application/json;charset=UTF-8
                    [content-length] => 294
                    [server] => Jetty(9.2.20.v20161216)
                )

        )

    [body] => {"errors":[{"code":"INVALID_DOCUMENT","keyPath":["components",1,"components",13,"text"],"value":"","message":"\"text\" was \"\" should be not (null or an empty string)"},{"code":"INVALID_DOCUMENT","keyPath":["components",1,"components",13],"message":"no components defined for role=heading2"}]}
    [response] => Array
        (
            [code] => 400
            [message] => Bad Request
        )

    [cookies] => Array
        (
        )

    [filename] => 
    [http_response] => WP_HTTP_Requests_Response Object
        (
            [response:protected] => Requests_Response Object
                (
                    [body] => {"errors":[{"code":"INVALID_DOCUMENT","keyPath":["components",1,"components",13,"text"],"value":"","message":"\"text\" was \"\" should be not (null or an empty string)"},{"code":"INVALID_DOCUMENT","keyPath":["components",1,"components",13],"message":"no components defined for role=heading2"}]}
                    [raw] => HTTP/1.1 400 Bad Request
Date: Thu, 13 Apr 2017 20:05:23 GMT
Request-Id: 7340acae-14e5-442e-9cef-c8ab51168aa0
Content-Type: application/json;charset=UTF-8
Content-Length: 294
Server: Jetty(9.2.20.v20161216)

{"errors":[{"code":"INVALID_DOCUMENT","keyPath":["components",1,"components",13,"text"],"value":"","message":"\"text\" was \"\" should be not (null or an empty string)"},{"code":"INVALID_DOCUMENT","keyPath":["components",1,"components",13],"message":"no components defined for role=heading2"}]}
                    [headers] => Requests_Response_Headers Object
                        (
                            [data:protected] => Array
                                (
                                    [date] => Array
                                        (
                                            [0] => Thu, 13 Apr 2017 20:05:23 GMT
                                        )

                                    [request-id] => Array
                                        (
                                            [0] => 7340acae-14e5-442e-9cef-c8ab51168aa0
                                        )

                                    [content-type] => Array
                                        (
                                            [0] => application/json;charset=UTF-8
                                        )

                                    [content-length] => Array
                                        (
                                            [0] => 294
                                        )

                                    [server] => Array
                                        (
                                            [0] => Jetty(9.2.20.v20161216)
                                        )

                                )

                        )

                    [status_code] => 400
                    [protocol_version] => 1.1
                    [success] => 
                    [redirects] => 0
                    [url] => https://news-api.apple.com/channels/9b8d307a-4037-4f62-8628-687251037112/articles
                    [history] => Array
                        (
                        )

                    [cookies] => Requests_Cookie_Jar Object
                        (
                            [cookies:protected] => Array
                                (
                                )

                        )

                )

            [filename:protected] => 
            [data] => 
            [headers] => 
            [status] => 
        )

)

Request Meta:

Array
(
    [data] => Array
        (
            [links] => Array
                (
                    [sections] => Array
                        (
                            [0] => https://news-api.apple.com/sections/2d56ea70-1322-3b0f-bc49-6192a43d3b7e
                            [1] => https://news-api.apple.com/sections/a7a4def0-2f88-3df7-a545-eee3774d531f
                        )

                )

            [isPreview] => 1
        )

)

Image Settings:
Use Remote images enabled 

JSON:
{"version":"1.1","identifier":"post-19955","language":"en","title":"Mercury Retrograde Taurus Aries","documentStyle":{"backgroundColor":"#fafafa"},"layout":{"columns":7,"width":1024,"margin":100,"gutter":20},"components":[{"role":"header","layout":"headerPhotoLayout","components":[{"role":"photo","layout":"headerPhotoLayout","URL":"http:\/\/ayrial.com\/wp-content\/uploads\/2017\/04\/mercurygod.jpg"}],"behavior":{"type":"parallax","factor":0.8}},{"role":"container","layout":{"columnSpan":7,"columnStart":0,"ignoreDocumentMargin":true},"style":{"backgroundColor":"#fafafa"},"components":[{"role":"title","text":"Mercury Retrograde Taurus Aries","textStyle":"default-title","layout":"title-layout"},{"role":"byline","text":"by Admin | Apr 11, 2017 | 12:40 PM","textStyle":"default-byline","layout":"byline-layout"},{"role":"heading1","text":"Mercury Retrograde Taurus Aries: Reevaluate Values and Reassess your Passions","format":"markdown","textStyle":"default-heading-1","layout":"heading-layout"},{"role":"photo","URL":"http:\/\/ayrial.com\/wp-content\/uploads\/2015\/11\/Ainslie-Faust2-e1447630168926.png","layout":"anchor-layout-left","anchor":{"targetAnchorPosition":"center","rangeStart":0,"rangeLength":1,"targetComponentIdentifier":"component-bceb745d0bf5ed59ca7d7b35b40c0a60"}},{"role":"body","text":"[**AYRIAL**](http:\/\/ayrial.com), the leading online body, mind and spirit community features a revealing look at Mercury Retrograde.\n\n**Ainslie Faust, MA, PhD. **is an intuitive, Jungian-based astrologer with over twenty years experience in astrological counseling**. ** Follow Ainslie","format":"markdown","textStyle":"dropcapBodyStyle","layout":"body-layout","identifier":"component-bceb745d0bf5ed59ca7d7b35b40c0a60"},{"role":"heading4","text":"Share this Awesome Story!","format":"markdown","textStyle":"default-heading-4","layout":"heading-layout"},{"role":"heading1","text":"Mercury Retrograde Taurus Aries","format":"markdown","textStyle":"default-heading-1","layout":"heading-layout"},{"role":"body","text":"Mercury Retrograde Taurus Aries begins today at 4:14 PM PT. The phenomenon of Mercury Retrograde occurs when the planet appears to stand still in the sky and then slowly begins to move backwards, picking up speed as it goes. The slower the apparent motion, the more powerful the influence. Thus the day Mercury turns retrograde and the day it turns direct (May 3) are usually the most dramatic. The backward motion is an illusion, based on the geocentric theory of the solar system, when scientists thought that the planets revolved around the Earth instead of the Earth revolving around the Sun. Mercury Retrograde Taurus\/Aries occurs at 4:51\u00b0 Taurus so if you have fixed angles or personal planets (Scorpio, Taurus, Leo, Aquarius), then you may feel this more than others. (If you want to find out more about your chart, then you can **schedule a reading** with me.) Mercury Retrograde in Taurus asks us to think about what we really value in concrete terms, not just what we say, but what we do, not what is expedient, but what is in alignment with our integrity.","format":"markdown","textStyle":"default-body","layout":"body-layout"},{"role":"body","text":"On April 20th, Mercury will move back into Aries, turning direct on May 3rd at 24:16 \u00b0 Aries. Once Mercury moves back into this fiery sign miscommunications and mistakes will stem more from rashness and exaggeration then from what we value and possess. Think before you speak or write with Mercury Retrograde in Aries. Mercury Retrograde in Aries asks us to express our unique powers of observation and criticism, just use them on yourself, in introspection, instead of inflicting them on those around you. It is a good idea to delay shopping, especially for anything with moving parts, until May 21st when the shadow ends. Also check all communications and documents for errors, watch out for lost mail, and travel snafus as well. Look for friends and objects from the past to resurface, and be very careful when driving as it is notorious for fender benders.","format":"markdown","textStyle":"default-body","layout":"body-layout"},{"role":"heading3","text":"Mercury Retrograde Taurus Aries: Reevaluate Values and your Passions @ainsliefaust #mercuryretrograde @AYRIAL7 Tweet","format":"markdown","textStyle":"default-heading-3","layout":"heading-layout"},{"role":"photo","URL":"http:\/\/ayrial.com\/wp-content\/uploads\/2016\/01\/Ainslie-Faust-blog-sm.png","layout":"anchor-layout-left","anchor":{"targetAnchorPosition":"center","rangeStart":0,"rangeLength":1,"targetComponentIdentifier":"component-8ee96c7bc3d4dfd938b31f53a3f21576"}},{"role":"body","text":"This post **[Mercury Retrograde Taurus Aries: Reevaluate Values and Reassess your Passions](http:\/\/astroainslie.us11.list-manage.com\/track\/click?u=55392136c383fb8337a5e1f58&id=befe7117d7&e=5289e635df) **appeared first on **[AstroAinslie ](http:\/\/astroainslie.us11.list-manage.com\/track\/click?u=55392136c383fb8337a5e1f58&id=08cda00c3c&e=5289e635df)**.\n\n[**Ainslie Faust**](http:\/\/ayrial.com\/jungian-astrologer-ainslie-faust\/) is an intuitive, Jungian-based astrologer. Ainslie holds an MA in counseling Psychology and a PhD in Philosophy and Religion with a concentration on symbol systems and Jungian Psychology. With over twenty-five years experience in astrological counseling, Ainslie brings a unique, artistic perspective, to her workshops and readings. [**_Follow Ainslie_**](https:\/\/twitter.com\/ainsliefaust\/)","format":"markdown","textStyle":"default-body","layout":"body-layout","identifier":"component-8ee96c7bc3d4dfd938b31f53a3f21576"},{"role":"container","layout":{"columnStart":0,"columnSpan":6,"margin":{"bottom":"20","top":"20"}},"style":{"backgroundColor":"#e1e1e1","border":{"all":{"width":"3","style":"solid","color":"#4f4f4f"},"bottom":false,"right":false,"top":false}},"components":[{"role":"quote","text":"[Ayrial](https:\/\/www.facebook.com\/ayrial7)\n\n","format":"markdown","layout":"blockquote-layout","textStyle":"default-blockquote"}],"textStyle":"default-blockquote"},{"role":"heading2","text":"","format":"markdown","textStyle":"default-heading-2","layout":"heading-layout"},{"role":"photo","URL":"http:\/\/ayrial.com\/wp-content\/uploads\/2017\/02\/logo2x1.png","layout":"full-width-image"},{"role":"heading2","text":"Visit Us +","format":"markdown","textStyle":"default-heading-2","layout":"heading-layout"},{"role":"heading2","text":"AYRIAL.com","format":"markdown","textStyle":"default-heading-2","layout":"heading-layout"},{"role":"photo","URL":"http:\/\/ayrial.com\/wp-content\/uploads\/2016\/09\/f.png","layout":"anchored-image"},{"role":"photo","URL":"http:\/\/ayrial.com\/wp-content\/uploads\/2016\/09\/l.png","layout":"anchored-image"},{"role":"photo","URL":"http:\/\/ayrial.com\/wp-content\/uploads\/2016\/09\/t.png","layout":"anchored-image"}]}],"componentTextStyles":{"default-heading-1":{"fontName":"AvenirNext-Bold","fontSize":48,"lineHeight":52,"textColor":"#333333","textAlignment":"left","tracking":0},"dropcapBodyStyle":{"textAlignment":"left","fontName":"AvenirNext-Regular","fontSize":18,"tracking":0,"lineHeight":24,"textColor":"#4f4f4f","linkStyle":{"textColor":"#428bca"},"paragraphSpacingBefore":18,"paragraphSpacingAfter":18,"dropCapStyle":{"numberOfLines":4,"numberOfCharacters":1,"padding":5,"fontName":"AvenirNext-Bold","textColor":"#4f4f4f","numberOfRaisedLines":0}},"default-body":{"textAlignment":"left","fontName":"AvenirNext-Regular","fontSize":18,"tracking":0,"lineHeight":24,"textColor":"#4f4f4f","linkStyle":{"textColor":"#428bca"},"paragraphSpacingBefore":18,"paragraphSpacingAfter":18},"default-heading-4":{"fontName":"AvenirNext-Bold","fontSize":21,"lineHeight":26,"textColor":"#333333","textAlignment":"left","tracking":0},"default-heading-3":{"fontName":"AvenirNext-Bold","fontSize":24,"lineHeight":28,"textColor":"#333333","textAlignment":"left","tracking":0},"default-blockquote":{"fontName":"AvenirNext-Regular","fontSize":18,"textColor":"#4f4f4f","lineHeight":24,"textAlignment":"left","tracking":0},"default-heading-2":{"fontName":"AvenirNext-Bold","fontSize":32,"lineHeight":36,"textColor":"#333333","textAlignment":"left","tracking":0},"default-title":{"fontName":"AvenirNext-Bold","fontSize":48,"lineHeight":52,"tracking":0,"textColor":"#333333","textAlignment":"left"},"default-byline":{"textAlignment":"left","fontName":"AvenirNext-Medium","fontSize":13,"lineHeight":24,"tracking":0,"textColor":"#7c7c7c"}},"componentLayouts":{"heading-layout":{"columnStart":0,"columnSpan":6,"margin":{"bottom":15,"top":15}},"anchored-image":{"margin":{"bottom":25,"top":25}},"body-layout":{"columnStart":0,"columnSpan":6,"margin":{"top":12,"bottom":12}},"body-layout-last":{"columnStart":0,"columnSpan":6,"margin":{"top":12,"bottom":30}},"blockquote-layout":{"contentInset":{"bottom":true,"left":true,"right":true,"top":true}},"full-width-image":{"margin":{"bottom":25,"top":25},"columnSpan":7,"columnStart":0},"anchor-layout-left":{"columnStart":0,"columnSpan":3},"headerPhotoLayout":{"ignoreDocumentMargin":true,"columnStart":0,"columnSpan":7},"headerBelowTextPhotoLayout":{"ignoreDocumentMargin":true,"columnStart":0,"columnSpan":7,"margin":{"top":30,"bottom":0}},"title-layout":{"margin":{"top":30,"bottom":0}},"byline-layout":{"margin":{"top":10,"bottom":10},"columnStart":0,"columnSpan":7}},"metadata":{"thumbnailURL":"http:\/\/ayrial.com\/wp-content\/uploads\/2017\/04\/mercurygod.jpg","dateCreated":"2017-04-11T16:40:21+00:00","dateModified":"2017-04-13T20:05:17+00:00","datePublished":"2017-04-11T16:40:21+00:00","canonicalURL":"http:\/\/ayrial.com\/mercury-retrograde-taurus-aries\/","generatorIdentifier":"publish-to-apple-news","generatorName":"Publish to Apple News","generatorVersion":"1.2.5"},"advertisingSettings":{"frequency":1,"layout":{"margin":{"top":15,"bottom":15}}}}

MIME request:
Authorization: HHMAC; key=26ab696e-f9cd-44cc-96f8-a2c8bb2fae1d; signature=eyjyeHSzR7vrVYB7WXs0b/4je+XV/w6ofproomz51Vo=; date=2017-04-13T20:05:23+00:00
Content-Length: 10355
Content-Type: multipart/form-data; boundary=c105e55081066384920275683e5c2014

--c105e55081066384920275683e5c2014
Content-Type: application/json
Content-Disposition: form-data; name=metadata

{"data":{"links":{"sections":["https:\/\/news-api.apple.com\/sections\/2d56ea70-1322-3b0f-bc49-6192a43d3b7e","https:\/\/news-api.apple.com\/sections\/a7a4def0-2f88-3df7-a545-eee3774d531f"]},"isPreview":true}}
--c105e55081066384920275683e5c2014
Content-Type: application/json
Content-Disposition: form-data; name=my_article; filename=article.json; size=9837

{"version":"1.1","identifier":"post-19955","language":"en","title":"Mercury Retrograde Taurus Aries","documentStyle":{"backgroundColor":"#fafafa"},"layout":{"columns":7,"width":1024,"margin":100,"gutter":20},"components":[{"role":"header","layout":"headerPhotoLayout","components":[{"role":"photo","layout":"headerPhotoLayout","URL":"http:\/\/ayrial.com\/wp-content\/uploads\/2017\/04\/mercurygod.jpg"}],"behavior":{"type":"parallax","factor":0.8}},{"role":"container","layout":{"columnSpan":7,"columnStart":0,"ignoreDocumentMargin":true},"style":{"backgroundColor":"#fafafa"},"components":[{"role":"title","text":"Mercury Retrograde Taurus Aries","textStyle":"default-title","layout":"title-layout"},{"role":"byline","text":"by Admin | Apr 11, 2017 | 12:40 PM","textStyle":"default-byline","layout":"byline-layout"},{"role":"heading1","text":"Mercury Retrograde Taurus Aries: Reevaluate Values and Reassess your Passions","format":"markdown","textStyle":"default-heading-1","layout":"heading-layout"},{"role":"photo","URL":"http:\/\/ayrial.com\/wp-content\/uploads\/2015\/11\/Ainslie-Faust2-e1447630168926.png","layout":"anchor-layout-left","anchor":{"targetAnchorPosition":"center","rangeStart":0,"rangeLength":1,"targetComponentIdentifier":"component-bceb745d0bf5ed59ca7d7b35b40c0a60"}},{"role":"body","text":"[**AYRIAL**](http:\/\/ayrial.com), the leading online body, mind and spirit community features a revealing look at Mercury Retrograde.\n\n**Ainslie Faust, MA, PhD. **is an intuitive, Jungian-based astrologer with over twenty years experience in astrological counseling**. ** Follow Ainslie","format":"markdown","textStyle":"dropcapBodyStyle","layout":"body-layout","identifier":"component-bceb745d0bf5ed59ca7d7b35b40c0a60"},{"role":"heading4","text":"Share this Awesome Story!","format":"markdown","textStyle":"default-heading-4","layout":"heading-layout"},{"role":"heading1","text":"Mercury Retrograde Taurus Aries","format":"markdown","textStyle":"default-heading-1","layout":"heading-layout"},{"role":"body","text":"Mercury Retrograde Taurus Aries begins today at 4:14 PM PT. The phenomenon of Mercury Retrograde occurs when the planet appears to stand still in the sky and then slowly begins to move backwards, picking up speed as it goes. The slower the apparent motion, the more powerful the influence. Thus the day Mercury turns retrograde and the day it turns direct (May 3) are usually the most dramatic. The backward motion is an illusion, based on the geocentric theory of the solar system, when scientists thought that the planets revolved around the Earth instead of the Earth revolving around the Sun. Mercury Retrograde Taurus\/Aries occurs at 4:51\u00b0 Taurus so if you have fixed angles or personal planets (Scorpio, Taurus, Leo, Aquarius), then you may feel this more than others. (If you want to find out more about your chart, then you can **schedule a reading** with me.) Mercury Retrograde in Taurus asks us to think about what we really value in concrete terms, not just what we say, but what we do, not what is expedient, but what is in alignment with our integrity.","format":"markdown","textStyle":"default-body","layout":"body-layout"},{"role":"body","text":"On April 20th, Mercury will move back into Aries, turning direct on May 3rd at 24:16 \u00b0 Aries. Once Mercury moves back into this fiery sign miscommunications and mistakes will stem more from rashness and exaggeration then from what we value and possess. Think before you speak or write with Mercury Retrograde in Aries. Mercury Retrograde in Aries asks us to express our unique powers of observation and criticism, just use them on yourself, in introspection, instead of inflicting them on those around you. It is a good idea to delay shopping, especially for anything with moving parts, until May 21st when the shadow ends. Also check all communications and documents for errors, watch out for lost mail, and travel snafus as well. Look for friends and objects from the past to resurface, and be very careful when driving as it is notorious for fender benders.","format":"markdown","textStyle":"default-body","layout":"body-layout"},{"role":"heading3","text":"Mercury Retrograde Taurus Aries: Reevaluate Values and your Passions @ainsliefaust #mercuryretrograde @AYRIAL7 Tweet","format":"markdown","textStyle":"default-heading-3","layout":"heading-layout"},{"role":"photo","URL":"http:\/\/ayrial.com\/wp-content\/uploads\/2016\/01\/Ainslie-Faust-blog-sm.png","layout":"anchor-layout-left","anchor":{"targetAnchorPosition":"center","rangeStart":0,"rangeLength":1,"targetComponentIdentifier":"component-8ee96c7bc3d4dfd938b31f53a3f21576"}},{"role":"body","text":"This post **[Mercury Retrograde Taurus Aries: Reevaluate Values and Reassess your Passions](http:\/\/astroainslie.us11.list-manage.com\/track\/click?u=55392136c383fb8337a5e1f58&id=befe7117d7&e=5289e635df) **appeared first on **[AstroAinslie ](http:\/\/astroainslie.us11.list-manage.com\/track\/click?u=55392136c383fb8337a5e1f58&id=08cda00c3c&e=5289e635df)**.\n\n[**Ainslie Faust**](http:\/\/ayrial.com\/jungian-astrologer-ainslie-faust\/) is an intuitive, Jungian-based astrologer. Ainslie holds an MA in counseling Psychology and a PhD in Philosophy and Religion with a concentration on symbol systems and Jungian Psychology. With over twenty-five years experience in astrological counseling, Ainslie brings a unique, artistic perspective, to her workshops and readings. [**_Follow Ainslie_**](https:\/\/twitter.com\/ainsliefaust\/)","format":"markdown","textStyle":"default-body","layout":"body-layout","identifier":"component-8ee96c7bc3d4dfd938b31f53a3f21576"},{"role":"container","layout":{"columnStart":0,"columnSpan":6,"margin":{"bottom":"20","top":"20"}},"style":{"backgroundColor":"#e1e1e1","border":{"all":{"width":"3","style":"solid","color":"#4f4f4f"},"bottom":false,"right":false,"top":false}},"components":[{"role":"quote","text":"[Ayrial](https:\/\/www.facebook.com\/ayrial7)\n\n","format":"markdown","layout":"blockquote-layout","textStyle":"default-blockquote"}],"textStyle":"default-blockquote"},{"role":"heading2","text":"","format":"markdown","textStyle":"default-heading-2","layout":"heading-layout"},{"role":"photo","URL":"http:\/\/ayrial.com\/wp-content\/uploads\/2017\/02\/logo2x1.png","layout":"full-width-image"},{"role":"heading2","text":"Visit Us +","format":"markdown","textStyle":"default-heading-2","layout":"heading-layout"},{"role":"heading2","text":"AYRIAL.com","format":"markdown","textStyle":"default-heading-2","layout":"heading-layout"},{"role":"photo","URL":"http:\/\/ayrial.com\/wp-content\/uploads\/2016\/09\/f.png","layout":"anchored-image"},{"role":"photo","URL":"http:\/\/ayrial.com\/wp-content\/uploads\/2016\/09\/l.png","layout":"anchored-image"},{"role":"photo","URL":"http:\/\/ayrial.com\/wp-content\/uploads\/2016\/09\/t.png","layout":"anchored-image"}]}],"componentTextStyles":{"default-heading-1":{"fontName":"AvenirNext-Bold","fontSize":48,"lineHeight":52,"textColor":"#333333","textAlignment":"left","tracking":0},"dropcapBodyStyle":{"textAlignment":"left","fontName":"AvenirNext-Regular","fontSize":18,"tracking":0,"lineHeight":24,"textColor":"#4f4f4f","linkStyle":{"textColor":"#428bca"},"paragraphSpacingBefore":18,"paragraphSpacingAfter":18,"dropCapStyle":{"numberOfLines":4,"numberOfCharacters":1,"padding":5,"fontName":"AvenirNext-Bold","textColor":"#4f4f4f","numberOfRaisedLines":0}},"default-body":{"textAlignment":"left","fontName":"AvenirNext-Regular","fontSize":18,"tracking":0,"lineHeight":24,"textColor":"#4f4f4f","linkStyle":{"textColor":"#428bca"},"paragraphSpacingBefore":18,"paragraphSpacingAfter":18},"default-heading-4":{"fontName":"AvenirNext-Bold","fontSize":21,"lineHeight":26,"textColor":"#333333","textAlignment":"left","tracking":0},"default-heading-3":{"fontName":"AvenirNext-Bold","fontSize":24,"lineHeight":28,"textColor":"#333333","textAlignment":"left","tracking":0},"default-blockquote":{"fontName":"AvenirNext-Regular","fontSize":18,"textColor":"#4f4f4f","lineHeight":24,"textAlignment":"left","tracking":0},"default-heading-2":{"fontName":"AvenirNext-Bold","fontSize":32,"lineHeight":36,"textColor":"#333333","textAlignment":"left","tracking":0},"default-title":{"fontName":"AvenirNext-Bold","fontSize":48,"lineHeight":52,"tracking":0,"textColor":"#333333","textAlignment":"left"},"default-byline":{"textAlignment":"left","fontName":"AvenirNext-Medium","fontSize":13,"lineHeight":24,"tracking":0,"textColor":"#7c7c7c"}},"componentLayouts":{"heading-layout":{"columnStart":0,"columnSpan":6,"margin":{"bottom":15,"top":15}},"anchored-image":{"margin":{"bottom":25,"top":25}},"body-layout":{"columnStart":0,"columnSpan":6,"margin":{"top":12,"bottom":12}},"body-layout-last":{"columnStart":0,"columnSpan":6,"margin":{"top":12,"bottom":30}},"blockquote-layout":{"contentInset":{"bottom":true,"left":true,"right":true,"top":true}},"full-width-image":{"margin":{"bottom":25,"top":25},"columnSpan":7,"columnStart":0},"anchor-layout-left":{"columnStart":0,"columnSpan":3},"headerPhotoLayout":{"ignoreDocumentMargin":true,"columnStart":0,"columnSpan":7},"headerBelowTextPhotoLayout":{"ignoreDocumentMargin":true,"columnStart":0,"columnSpan":7,"margin":{"top":30,"bottom":0}},"title-layout":{"margin":{"top":30,"bottom":0}},"byline-layout":{"margin":{"top":10,"bottom":10},"columnStart":0,"columnSpan":7}},"metadata":{"thumbnailURL":"http:\/\/ayrial.com\/wp-content\/uploads\/2017\/04\/mercurygod.jpg","dateCreated":"2017-04-11T16:40:21+00:00","dateModified":"2017-04-13T20:05:17+00:00","datePublished":"2017-04-11T16:40:21+00:00","canonicalURL":"http:\/\/ayrial.com\/mercury-retrograde-taurus-aries\/","generatorIdentifier":"publish-to-apple-news","generatorName":"Publish to Apple News","generatorVersion":"1.2.5"},"advertisingSettings":{"frequency":1,"layout":{"margin":{"top":15,"bottom":15}}}}
--c105e55081066384920275683e5c2014--

**Comment by kevinfodness** [comment] 2017-04-18 15:15
Looks like you have a blank text node somewhere in your document, which means you are encountering #205.

Can you send a pastebin.com link to the text content of your post (from the Text tab in the content editor) so I can try to reproduce locally? I've seen this behavior occur with complex tag nesting, for example.

**Comment by VenusVenus** [comment] 2017-04-18 18:44
Thank you for your assistance.  Here’s my pastebin.com link:

 

https://pastebin.com/XsuCLwFS

 

Regards, 

Katie

**Comment by kevinfodness** [comment] 2017-04-18 19:19
Hi @VenusVenus—

You're actually running into #320. You can fix this by making sure that your images are not wrapped in heading tags (in this case, an H2 around `logo2x1.png`). A fix for this will be part of a future version of the plugin, but we don't have a specific timeframe in mind at the moment.

Good luck!

**Closed by kevinfodness** 2017-04-18 19:19 UTC
