### ISSUE TITLE
Not all articles publishing - Multi author

### ISSUE THREAD

**Issue by vincepettit** [alleyinteractive/apple-news#474] opened 2018-05-03 15:48 UTC
I have auto publish set but very often have articles that aren't published. It is a multi-author blog, with different access levels, would this have any effect on articles being published to Apple news?

It doesn't say there has been an error it just says that the published state is 'Never' for some.

**Comment by jnsprngs** [comment] 2018-05-04 15:11
I am experiencing the same issue (thinkprogress.org). There is no apparent error. It seems like the system is no longer attempting to auto-publish. If I go in and manually publish, it works without issue.

Also note that articles were auto-publishing before. They stopped without notice.

**Comment by jnsprngs** [comment] 2018-05-04 16:34
I think this ticket is duplicate to https://github.com/alleyinteractive/apple-news/issues/420

**Comment by kevinfodness** [comment] 2018-05-14 14:10
Yes, this is a dupe of #420, which is under active development for the next release. Thanks for the report. You can follow #420 for updates.

**Closed by kevinfodness** 2018-05-14 14:10 UTC
