### ISSUE TITLE
There has been an error with the Apple News API:

### ISSUE THREAD

**Issue by tomgreenhill** [alleyinteractive/apple-news#923] opened 2022-02-11 15:45 UTC
Hi, 

Our site just started to receive issues when publishing articles. The following error message is received, was using 2.3.1 on WP 5.9 but downgraded to 2.3.0 to see if there was an issue with a recent update. 

![Screenshot 2022-02-11 at 15 43 54](https://user-images.githubusercontent.com/1922302/153622571-d6e00173-7706-4d2b-95be-2d9a1547812a.png)

If you need anything else please do let me know.

Thanks in advance, 
Tom

**Comment by kevinfodness** [comment] 2022-03-03 20:04
This is a duplicate of #910 - I will address this as part of an update over the next week or two. Thanks for the issue report!

**Closed as completed** 2022-03-03 22:13 UTC
Labels: duplicate
