### ISSUE TITLE
Customization of text flow around images

### ISSUE THREAD

**Issue by patrickbajao** [alleyinteractive/apple-news#184] opened 2016-06-08 15:45 UTC
Hi,

I'm encountering the same thing as [this issue](https://github.com/alleyinteractive/apple-news/issues/130) but it was already closed. I'm using the latest version of the plugin (1.1.4) and latest version of the news preview app. I can also see this when I view the draft on my iPhone (iOS 9.3.2).

I can still see images show before a paragraph that is supposed to be shown before the image. Here's a [gist](https://gist.github.com/patrickbajao/1a30ef4353831e2c4d713e1834279f7f) containing the `article.json` and the markup in WP's text editor. I'm using bundled images but I didn't attach the bundled images here (let me know if you need them).

As you can see in the markup, the text `A view from Zambales:` is before the image. But in the JSON file, the image component is before the body component with text `A view from Zambales:\n\nIt\u2019s so nice!`. Looks like the text of the 2 paragraphs were merged for some reason.

Also, here are some screenshots to show the difference:

Web version:
![web](https://cloud.githubusercontent.com/assets/383183/15900270/8056c82e-2dd1-11e6-9139-a2559c6fd04d.png)

Apple News Preview:
![news_preview](https://cloud.githubusercontent.com/assets/383183/15900286/8bb2cff6-2dd1-11e6-8ad4-f5456eeb2060.png)

It seems that it was fixed before that's why the issue I referenced above was closed. Maybe this is a regression or something?

I also like to try and debug this myself but I don't know where to start.

Thanks,
Patrick

**Comment by bcampeau** [comment] 2016-06-08 15:48
The plugin attempts to calculate where paragraphs should be merged together in order to facilitate clean text wrapping around images at landscape and tablet screen widths. Looks like you have a single line of text as a paragraph above an image and I can totally see why those paragraphs would be merged together and appear below the image at the smallest breakpoint.

Unfortunately, I don't have an immediate solution for this though it's worth considering for a future version. In the meantime, have you considered adding that text as a caption instead?

**Comment by patrickbajao** [comment] 2016-06-08 16:34
Thanks for the quick response @bcampeau!

> The plugin attempts to calculate where paragraphs should be merged together in order to facilitate clean text wrapping around images at landscape and tablet screen widths. Looks like you have a single line of text as a paragraph above an image and I can totally see why those paragraphs would be merged together and appear below the image at the smallest breakpoint.

Hmm does this mean that if the paragraphs are longer they wouldn't be merged? I'm asking because I can also see this issue in my other articles with longer paragraphs. Just want to clarify since I might be misunderstanding it.

Here's another [gist](https://gist.github.com/patrickbajao/c5cafb084a1ae7dfd231c16c4f9e9cba) with 2 long paragraphs (~50 words each). The 2 paragraphs still get merged even if they're longer than a single line and the image component is placed before the body component. Looks like paragraphs will be merged regardless of length. I'm not sure if this is intended.

> Unfortunately, I don't have an immediate solution for this though it's worth considering for a future version. In the meantime, have you considered adding that text as a caption instead?

I just made this article to demonstrate the issue. I can definitely show single line of text as caption. For longer paragraphs, it'll still be an issue.

**Comment by bcampeau** [comment] 2016-06-08 20:03
We can consider re-evaluating this logic but for most people, it is creating a nice text flow around images at wider screen sizes. It would have to be carefully considered to not affect the majority of sites who are happy with the way it currently works.

You do have the ability to alter the JSON output in many different ways, either by filtering the final JSON via `apple_news_generate_json` or adding a custom component class. Some sites have also opted to do this to create a custom experience tailored to their content. 

I'll leave this issue open for now and we can consider what could be done to make this more customizable without writing code in a future plugin version.

**Comment by patrickbajao** [comment] 2016-06-09 07:32
Thanks for the suggestion and considering this as an enhancement, @bcampeau. I understand that it doesn't really look that bad especially when viewed on landscape or tablet. I'll look into customizing the JSON output for now.

Is it possible to know where the code for merging paragraphs is? I'm just curious.

**Comment by bcampeau** [comment] 2016-06-09 14:21
https://github.com/alleyinteractive/apple-news/blob/master/includes/apple-exporter/builders/class-components.php#L37-L156

**Comment by kevinfodness** [comment] 2017-01-14 03:33
Hi @patrickbajao - this behavior has been fixed in the latest release (1.2.1). I'm going to close this issue. If you notice unexpected behaviors when running the new version, please open a new issue. Thanks!

**Closed by kevinfodness** 2017-01-14 03:33 UTC
Labels: enhancement
