### ISSUE TITLE
Cryptic "You'll need to install Xcode 7" error message when opening News Preview

### ISSUE THREAD

**Issue by danielbachhuber** [alleyinteractive/apple-news#285] opened 2017-01-24 19:57 UTC
When I try to open News Preview, I see this error:

![image](https://cloud.githubusercontent.com/assets/36432/22264238/1b4c8670-e22c-11e6-8dfb-9a4091c70c61.png)

I've had Xcode installed though:

![image](https://cloud.githubusercontent.com/assets/36432/22264267/3354721e-e22c-11e6-94fa-7db72371f458.png)

Have you run into this before? Any ideas on how to resolve?

**Comment by bcampeau** [comment] 2017-01-24 20:04
Yeah it's not really a plugin issue, it's an Apple requirement. News Preview needs the Simulator which is bundled with Xcode.

**Comment by danielbachhuber** [comment] 2017-01-24 21:38
> News Preview needs the Simulator which is bundled with Xcode.

Xcode is installed. This is destroying me.

**Comment by bcampeau** [comment] 2017-01-24 21:41
Best bet is to start here: https://forums.developer.apple.com/community/distribution/apple-news/. Apple is usually responsive with feedback.

**Comment by bcampeau** [comment] 2017-01-24 21:43
Looks like there has been one thread about a similar issue, though no resolution: https://forums.developer.apple.com/thread/65481

**Comment by danielbachhuber** [comment] 2017-01-24 21:43
I have a support thread going with Apple. Here's the screencast I just sent: http://quick.as/yvvijjl3

**Comment by danielbachhuber** [comment] 2017-01-24 21:43
Yep, I saw that thread before.

**Comment by bcampeau** [comment] 2017-02-10 01:52
@danielbachhuber you ever get clarity on this? Thanks!

**Comment by danielbachhuber** [comment] 2017-02-10 14:57
Nope :( Never figured it out.

**Comment by bcampeau** [comment] 2017-02-10 15:00
That's unfortunate. I'm going to close it out since it's not directly related to the plugin, but feel free to respond if you ever do get an answer. Unfortunately we've not been able to replicate it.

**Comment by kevinfodness** [comment] 2017-05-11 13:51
I'm reopening this, because now it's happened to me more than once. I'm filing a support request with Apple. I believe it's related to either Xcode or Command Line Tools updates through the App Store causing macOS to "lose track" of Xcode at some level. I've had success in (temporarily) getting everything working again by uninstalling Xcode, restarting, and then reinstalling via the App Store.

**Comment by mslinnea** [comment] 2017-05-26 16:33
I am also experiencing this issue.  @kevinfodness I followed your steps outlined above, uninstalled Xcode, restarted, and then reinstalled, but unfortunately, it didn't solve the issue.

**Comment by mslinnea** [comment] 2017-06-29 17:18
Updating to Xcode 8.3.3 fixed this issue for me!  Anyone still having issues?

**Comment by danielbachhuber** [comment] 2017-06-29 17:27
Yes, I get the same error as before.

**Comment by danielbachhuber** [comment] 2017-06-29 17:35
Also, I updated to News Preview 1.3.6 and get the same error.

Does Alley have a contact at Apple we could run this issue past?

**Comment by kevinfodness** [comment] 2017-06-29 17:53
Hi @danielbachhuber—

I've actually got a support thread going for this, but I don't have reproduction steps. They recommended that I provide a sysdiagnose and system information report, but by that time, I had already uninstalled and reinstalled XCode, so they wouldn't have been relevant.

If you're willing to send me those reports from your system, I can forward them to Apple. I'll reach out to you under separate cover to ensure transmission is secure.

**Comment by danielbachhuber** [comment] 2017-06-29 19:07
> If you're willing to send me those reports from your system, I can forward them to Apple. I'll reach out to you under separate cover to ensure transmission is secure.

Yes, I've emailed them to you.

**Comment by rahulsprajapati** [comment] 2017-06-30 13:32
Hello guys,
I faced same error but found the workaround here:

Try to run this in terminal:
> defaults write com.apple.news.preview xcodeOverride <path-to-xcode.app>

Ref: https://forums.developer.apple.com/thread/75086

**Comment by danielbachhuber** [comment] 2017-06-30 13:39
> Try to run this in terminal:

Worked for me — thanks @rahulsprajapati !

**Closed** 2017-06-30 14:07 UTC
Labels: help wanted
