### ISSUE TITLE
Auto-publish not working

### ISSUE THREAD

**Issue by jerrythompson** [alleyinteractive/apple-news#177] opened 2016-05-24 16:46 UTC
On Wordpress VIP and with automatically publish to Apple News and Asynchronously publish to Apple News both set to yes, posts are rarely ever published.  Currently publishing 150-200 posts per day and less than 5 ever successfully publish to Apple News automatically.

**Comment by bcampeau** [comment] 2016-05-24 17:15
Are these scheduled posts? This could be a duplicate of #116.

Do you have debug mode enabled? If not, you should enable it and check for the API responses.

**Closed** 2016-07-26 10:31 UTC
Labels: bug, duplicate
