### ISSUE TITLE
Where on here does it tell you to put your API and everything?

### ISSUE THREAD

**Issue by mrandrew7** [alleyinteractive/apple-news#370] opened 2017-05-10 19:08 UTC
Can someone help me where it tells you to put your API and other codes to publish from Wordpress to Apple News?

**Comment by kevinfodness** [comment] 2017-05-10 20:05
Closing as a duplicate of #369.

**Closed by kevinfodness** 2017-05-10 20:05 UTC

**Comment by mrandrew7** [comment] 2017-05-10 20:07
It's not duplicate.  Show me where it says where to put them PLEASE!

**Comment by kevinfodness** [comment] 2017-05-11 06:09
Hi @mrandrew7 — it's a duplicate because we're having the conversation in #369.
