### ISSUE TITLE
How can I test on lower environments without having those lower environment articles show up on the prod feed?

### ISSUE THREAD

**Issue by katkat100** [alleyinteractive/apple-news#1137] opened 2024-06-18 17:00 UTC
### Description

I wpuld like to test the format and functionality of this plugin on a lower environment wordpress setup without having lower environment articles show up on our prod apple news feed. Does anyone know a way this is possible?

**Comment by kevinfodness** [comment] 2024-06-18 21:18
Set all of the automatically publish/update/delete etc rules to "no" in the Apple News > Settings page, then when you want to test something:
- Publish the article in WordPress on the lower environment
- Check the box for Preview in the Apple News options for the article
- Manually publish the article to Apple News using the Apple News sidebar on the article edit screen
This will ensure that the article is published to your channel as a draft, which will let you test it without it being visible in your channel feed.

**Comment by katkat100** [comment] 2024-09-11 18:58
Thanks @kevinfodness for your help! I am struggling to find the way to publish the article from the edit screen. I have the preview option selected. Any help would be appreciated.
Also would you know if downloading the article from the Apple News Article list and viewing it News Preview is supposed to work?
<img width="291" alt="Screenshot 2024-09-11 at 11 55 54 AM" src="https://github.com/user-attachments/assets/3029a400-5a6e-41de-9fdc-dce107e3cc7e">

**Comment by mogmarsh** [comment] 2024-09-11 19:33
@katkat100 in this case "Publish" means WordPress publish, not Apple News publish. You have done this, since I see the Update button.
Downloading the article and viewing it News Preview should work, but there are some caveats. Any fonts you use that are not stock Apple News fonts need to exist in the same directory as the file. The file must be renamed to article.json. Images may need to be in the same directory as well, depending on how you have your image settings set, and whether or not News Preview can access the images from your lower environment (is there any basic authentication set up, etc.)

**Comment by kevinfodness** [comment] 2024-09-11 19:39
Additional info on how to do this is in our wiki here: https://github.com/alleyinteractive/apple-news/wiki/usage#troubleshooting

**Comment by katkat100** [comment] 2024-09-11 21:25
Thank you very much for your help! I was able to get a preview working on News Preview after updating the image urls and putting the things in the correct folder.
Currently we are on a RSS Feed to Apple News when we officially switch from rss to this plugin on prod what happens to the articles that were being supplied from the feed?

**Comment by kevinfodness** [comment] 2024-09-12 12:18
The articles that were being supplied from the feed should continue to exist on your channel, but new ones will appear as a result of pushing them via the plugin. Note that the plugin keeps track of the article it's associated with via postmeta, which won't apply to articles that were pulled in to Apple News via RSS, so if you update an article that was previously sent to Apple News via RSS, you may get an error that it failed to push to Apple News because it's a duplicate of an article that already exists (this is expected and fine). New articles should be able to be pushed without issue.

**Comment by katkat100** [comment] 2024-09-13 21:03
Thank you for all your help on this. I have another question regarding deleting articles. We were testing drafts and were able to get it show on the publisher drafted article list but when we deleted the article from the plugin it still shows live as the status. It was successfully removed from the draft list though. We also tried re-publishing it from the plugin and got the error `Skipped push of article 260727 to Apple News because it is already in sync.` Is there something we need to check or update to have the status reflect the actual status of the article?

**Comment by kevinfodness** [comment] 2024-09-16 13:59
In the settings screen, do you have all of the automatic settings set to "yes": automatically publish, update, delete, etc? If they are, and you make a change from the plugin, it should sync the status to Apple News and it should update the post in WordPress to indicate that it is no longer connected to a post on Apple News. If all of those are on, can you provide specific steps to reproduce?

**Comment by katkat100** [comment] 2024-09-16 17:41
![Screenshot 2024-09-16 at 10 37 23 AM](https://github.com/user-attachments/assets/8557dceb-0835-4d97-a4f4-e7d1e000b7be)
I turned on everything but the publish to and update options since we are still in a testing environment. I then clicked delete from Apple News Plugin Article List and got the confirmation that the article was deleted. The draft list confirmed that the article was no longer there but the status still says Live. The previously removed article status has now changed to `NOT_FOUND (keyPath articleId)`. So is it just a slower updating time for status then the actual action? Thank you for your help in straightening things out.

**Comment by kevinfodness** [comment] 2024-09-16 18:14
Ah, ok, I think I know what's going on. We cache the article status so we aren't hitting Apple's API for updates all the time, and we're probably failing to clear the article status after it's deleted in that way. Most of the time, articles are deleted from WordPress and are also deleted from Apple News - it's kind of rare for someone to delete an article on Apple News without also deleting it from WordPress, but it does happen from time to time.

**Comment by katkat100** [comment] 2024-09-16 19:10
Oh, I see. The other issue is that the article after being deleted from Apple News can't be republished because it's already in sync. `Skipped push of article 260727 to Apple News because it is already in sync.` Is there process that we can do in case we delete from Apple News plugin and then wanted to publish it, like something published to early so we deleted it and wanted to publish when it was time?

**Comment by kevinfodness** [comment] 2024-09-19 14:23
If it's deleted from Apple News and the postmeta linking it to Apple News in WordPress is properly reset, then you can publish it to Apple News again using one of these methods:
- If the article was a draft, transitioning it to Publish status will automatically publish it to Apple News as long as you have the plugin configured to automatically send to Apple News on publish
- If the article was already published in WordPress, or if you aren't automatically pushing, you can click the Publish link in the Apple News article list in the WordPress admin to send it up.

**Comment by katkat100** [comment] 2024-09-24 17:39
Thank you for showing how to republish an article I am just unsure how I reset postmeta for an article? Also where is Channel Default being set I couldn't find it in settings or in News Publisher?

**Comment by kevinfodness** [comment] 2024-09-26 15:13
Resetting postmeta has to be done via the database or WP-CLI - anything with an `apple_news_` prefix and associated with the post ID you want to reset is safe to delete.

What do you mean by Channel Default? Do you mean default section?

**Comment by katkat100** [comment] 2024-10-02 20:37
Channel Default as in the apple news side bar options for the dropdown like the attached image. 
<img width="280" alt="Screenshot 2024-10-02 at 1 29 39 PM" src="https://github.com/user-attachments/assets/e1ff20f6-ca8f-4b0e-ac9d-fd524261476d">

We were able to get to production environment with the plugin but we ran into an error with Image Blocks where the layout value in the article.json is `layout: []`. How can I prevent this from happening, is it a setting?
The full block is like this
`{
          "role": "container",
          "components": [
            {
              "role": "photo",
              "URL": [url],
              "layout": "full-width-image-with-caption",
              "caption": {
                "format": "html",
                "text": "<span class=\"media-credit\"></span>",
                "textStyle": { "fontName": "HelveticaNeue-Italic" }
              }
            },
            {
              "role": "caption",
              "text": "<span class=\"media-credit\"></span>",
              "format": "html",
              "textStyle": {
                "textAlignment": "left",
                "fontName": "HelveticaNeue-Italic",
                "fontSize": 13,
                "tracking": 0,
                "lineHeight": 16,
                "textColor": "#484c51"
              },
              "layout": { "margin": { "bottom": 25 } }
            }
          ],
          "layout": []
        }`

**Closed as completed** 2024-11-14 17:37 UTC
Labels: help wanted
