### ISSUE TITLE
done button

### ISSUE THREAD

**Issue by iamkingsleyf** [alleyinteractive/apple-news#536] opened 2018-07-06 00:29 UTC
Hello;

Please the **done** when clicked on does nothing, is this normal? https://imgur.com/a/EhqNesD

Thanks

**Comment by gdvine** [comment] 2018-07-31 12:31
perhaps this is a subset of this bug? https://github.com/alleyinteractive/apple-news/issues/542

**Comment by kevinfodness** [comment] 2018-09-07 09:59
Duplicate of #452.

**Closed by kevinfodness** 2018-09-07 09:59 UTC
