### ISSUE TITLE
News is publised by not showing on icloud new publisher section

### ISSUE THREAD

**Issue by abuzer** [alleyinteractive/apple-news#455] opened 2018-03-15 17:39 UTC
When publishing from Wordpress admin panel. It shows "Your article has been pushed successfully!"  but there is not news in drafts in news publisher page.

And the other statuses are:

NOT_FOUND (keyPath articleId) | Published

**Comment by kevinfodness** [comment] 2018-09-07 08:56
Closing as a dupe of #508.

**Closed by kevinfodness** 2018-09-07 08:56 UTC
