### ISSUE TITLE
Auto publish to Apple News stopped working in latest update

### ISSUE THREAD

**Issue by yuppyfarmer** [alleyinteractive/apple-news#669] opened 2019-09-09 15:12 UTC
The "Automatically publish to Apple News when published in WordPress" has stopped working since the latest apple-news release was installed (2.0.1).

Downgrading to 1.4.4 does not seem to fix the issue.

**Comment by hrkhal** [comment] 2019-09-10 13:43
Can confirm this has also happened for us in testing when using the classic editor.  Rolling back to `1.4.3` does allow for articles authored in the classic editor to auto-publish.

The auto-publish only works for us in `2.0.1` when the site is loading Gutenberg via `wpcom_vip_load_gutenberg( [ 'load' => 1 ] );`

We need the auto-publish functionality to work for articles created in both the classic editor and Gutenberg.

**Comment by kevinfodness** [comment] 2019-09-10 14:06
We will look into this on a priority basis.

**Comment by jcdestro81** [comment] 2019-09-17 17:59
I confirm the same problem... the last Apple-news release 2.0.1 don't AUTOMATICALLY PUBLISH to APPLE NEWS when published on Wordpress.

**Comment by jomurgel** [comment] 2019-09-17 21:04
Thanks for the confirmation. We have an update to release in 2.0.2 which should resolve this issue on environments like VIP where a mix of Gutenberg and Classic posts are present.

**Comment by zml440** [comment] 2019-09-18 20:48
> Can confirm this has also happened for us in testing when using the classic editor. Rolling back to `1.4.3` does allow for articles authored in the classic editor to auto-publish.
> 
> The auto-publish only works for us in `2.0.1` when the site is loading Gutenberg via `wpcom_vip_load_gutenberg( [ 'load' => 1 ] );`
> 
> We need the auto-publish functionality to work for articles created in both the classic editor and Gutenberg.

Stupid question - but I am new to this whole coding and API thing and have very little knowledge about what I'm doing. How do I downgrade to a previous version of the plugin? Thank you!

**Comment by zml440** [comment] 2019-09-18 21:10
@hrkhal @jcdestro81 

Hi. I am new to coding/API in general but have some (very limited) knowledge. I have a confirmed account w/ Apple News and am able to publish to the channel using Hubspot via an RSS feed, so I know the issue is not on Apple's end. Our business is switching over to WP from Hubspot so I am trying to move all blog to WP as we transition.

I have double-checked that all of my API info was entered correctly into the WP plugin settings and still having issue as you all have experienced. I tried rolling back to 1.4.3 and am still getting the same error. Is there something I need to do in specific besides just trying to "publish" thru 1.4.3 plugin? I am not trying to use autopublish but I can't get anything to post even manually. 

Wondering if I am missing additional steps I need to take (e.g., JSON edits, adding some type of WP RSS feed to Apple News account settings, etc.)

Thanks so much! Sorry for the stupid question.

**Comment by kevinfodness** [comment] 2019-09-19 20:25
@zml440 - if you can't get anything to publish, even manually, and you're using v1.4.3 of the plugin, then that feels like a different issue to me. Would you mind opening a new GitHub issue request and posting any errors you receive on publish there? You can also click on Apple News on the menu on the left and see a list of your articles and attempt to publish there, and it will report the status of the article using Apple's API in a column.

**Comment by dartiss** [comment] 2019-09-30 06:40
@kevinfodness @jomurgel are you planning on pushing the 2.0.2 release out to WordPress.org?

**Comment by kevinfodness** [comment] 2019-09-30 14:47
Yes - in my pre-release testing I discovered a bug, and the fix is in code review now. I'm doing some final checks this morning in preparation for a release today.

**Comment by kevinfodness** [comment] 2019-09-30 19:25
Hi all - v2.0.2 just released, and I've confirmed that autopublish works in the following scenarios:

- WP >= 5.0 with Gutenberg enabled
- WP >= 5.0 with the Classic Editor plugin enabled
- WP >= 5.0 on VIP Go with Gutenberg Ramp enabling Gutenberg
- WP >= 5.0 on VIP Go with Gutenberg Ramp disabling Gutenberg
- WP 4.9.x (no Gutenberg)

Please let me know if there are any issues with the new version.

**Comment by kevinfodness** [comment] 2019-10-03 01:11
I also released v2.0.3 just now to fix some JS errors that some users were reporting. I'm going to close this ticket, but please let me know if there are any issues with v2.0.3.

**Closed by kevinfodness** 2019-10-03 01:11 UTC
Labels: bug, gutenberg
