### ISSUE TITLE
The link you followed has expired.

### ISSUE THREAD

**Issue by iamkingsleyf** [alleyinteractive/apple-news#537] opened 2018-07-06 22:22 UTC
Hello;

We are having the following error <strong>"The link you followed has expired."</strong> when you click on publish post, this is happening across 2 sites and once the plugin is disabled it works fine. its happening on https://thegloor.com and https://healthable.org

Thanks

**Comment by iamkingsleyf** [comment] 2018-07-06 22:43
i found this also

https://wordpress.org/support/topic/plugin-conflict-200/

**Comment by iamkingsleyf** [comment] 2018-07-26 18:38
any update

**Comment by danielbachhuber** [comment] 2018-08-17 14:48
Duplicate of #544

**Closed** 2018-09-07 09:59 UTC
